### ISSUE TITLE
Request: Some games.

### ISSUE THREAD

**Issue by rodrigopill** [Tustin/PlayStationDiscord-Games#4]
Can you add Apex Legends and Star Wars Battlefront II? Please.

**Comment by Tustin** [comment]
Apex should be supported. I think the reason why it might not have shown up is because the old version of the program used a different URL to get the games.json file. I just released my rewrite which properly uses the games.json from this repo. However I'm not sure if BF2 is on the list but I can definitely add it if there's room.
